
// Objective-C API for talking to the following Go packages
//
//	github.com/scue/gobind-example/hello
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Hello_FRAMEWORK_H__
#define __Hello_FRAMEWORK_H__

#include "Hello.objc.h"
#include "universe.objc.h"

#endif
